name: regular-deployment
run-name: Deploying from main branch...

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    # runs-on: ubuntu-latest
    # hack to get around update TODO: fix for real
    runs-on: ubuntu-22.04

    permissions:
      deployments: write
